-- ============================================
-- Migration 004: Security hardening
-- - Restrict lessons.* read access to enrolled users / admins / preview only
-- - Lock down lesson_attachments to enrolled users / admins
-- - Make lesson-attachments storage bucket private
-- - Enrollment check on lesson_progress writes
-- - Public catalog uses lesson_summaries view (no sensitive fields)
-- ============================================

-- ============================================
-- 1. Helper: is_enrolled(course_id)
-- ============================================
create or replace function public.is_enrolled(p_course_id uuid)
returns boolean as $$
  select exists (
    select 1 from public.enrollments
    where user_id = auth.uid()
      and course_id = p_course_id
      and status = 'active'
      and (expires_at is null or expires_at > now())
  );
$$ language sql security definer stable;

-- ============================================
-- 2. LESSONS — replace permissive SELECT with strict policy
-- ============================================
drop policy if exists "Lessons visible for published courses" on public.lessons;

-- Admins always see everything
create policy "Lessons visible to admins"
  on public.lessons for select
  using (public.is_admin());

-- Preview lessons in published courses are visible to anyone
create policy "Preview lessons visible to all"
  on public.lessons for select
  using (
    is_preview = true
    and exists (
      select 1 from public.modules m
      join public.courses c on c.id = m.course_id
      where m.id = module_id and c.status = 'published'
    )
  );

-- Non-preview lessons require an active enrollment
create policy "Enrolled users can read course lessons"
  on public.lessons for select
  using (
    exists (
      select 1 from public.modules m
      where m.id = module_id and public.is_enrolled(m.course_id)
    )
  );

-- ============================================
-- 3. lesson_summaries view — safe metadata for catalog browsing
-- ============================================
-- Drops sensitive columns (mux_playback_id, content_html, download_url) so
-- non-enrolled users can still see the curriculum but not the actual content.
create or replace view public.lesson_summaries
with (security_invoker = false) as
  select
    l.id,
    l.module_id,
    l.title,
    l.description,
    l.lesson_type,
    l.duration_seconds,
    l.sort_order,
    l.is_preview
  from public.lessons l
  join public.modules m on m.id = l.module_id
  join public.courses c on c.id = m.course_id
  where c.status = 'published';

grant select on public.lesson_summaries to anon, authenticated;

-- ============================================
-- 4. LESSON ATTACHMENTS — restrict to enrolled / admin
-- ============================================
drop policy if exists "Attachments visible for published course lessons"
  on public.lesson_attachments;

create policy "Admins see all attachments"
  on public.lesson_attachments for select
  using (public.is_admin());

create policy "Enrolled users see course attachments"
  on public.lesson_attachments for select
  using (
    exists (
      select 1 from public.lessons l
      join public.modules m on m.id = l.module_id
      where l.id = lesson_id and public.is_enrolled(m.course_id)
    )
  );

-- ============================================
-- 5. lesson-attachments storage bucket — go private
-- ============================================
update storage.buckets set public = false where id = 'lesson-attachments';

-- Drop the old "Attachments are publicly accessible" select policy.
drop policy if exists "Attachments are publicly accessible" on storage.objects;

-- New: only admins can read directly. Students get files via signed URLs
-- generated by the /api/attachments/[id] route (which uses the service role
-- after checking enrollment), so no public/student-readable storage policy.
create policy "Admins can read lesson attachment files"
  on storage.objects for select
  using (bucket_id = 'lesson-attachments' and public.is_admin());

-- ============================================
-- 6. LESSON PROGRESS — require active enrollment to insert/update
-- ============================================
drop policy if exists "Users can insert own progress" on public.lesson_progress;
drop policy if exists "Users can update own progress" on public.lesson_progress;

create policy "Enrolled users can insert own progress"
  on public.lesson_progress for insert
  with check (
    auth.uid() = user_id
    and public.is_enrolled(course_id)
  );

create policy "Enrolled users can update own progress"
  on public.lesson_progress for update
  using (auth.uid() = user_id and public.is_enrolled(course_id));
